(define (square-sum-larger a b c)
    (define (square-sum x y)
        (+ (square x) (square y)))
    (if (> a b)
        (if (> b c)
            (square-sum a b)
            (square-sum a c))
        (if (> a c)
            (square-sum a b)
            (square-sum b c))))
